### ISSUE TITLE
Current version of kin-openapi does not have openapi3.Swagger type

### ISSUE THREAD

**Issue by kishaningithub** [MarioCarrion/todo-api-microservice-example#1]
Current version of github.com/getkin/kin-openapi/openapi which is v0.66.0 does not have openapi3.Swagger type

It would be great if [your blog](https://mariocarrion.com/2021/05/02/golang-microservices-rest-api-openapi3-swagger-ui.html) and this repo can be updated in line with the latest version

Also have linked your blog [here](https://github.com/getkin/kin-openapi/issues/380#issuecomment-879639671)

**Comment by kishaningithub** [comment]
As per this https://github.com/getkin/kin-openapi#v0610

openapi3.Swagger has been renamed to openapi3.T

**Comment by kishaningithub** [comment]
Also i feel the example can use  `openapi3gen.NewSchemaRefForValue` to auto generate schemas from go structs

https://pkg.go.dev/github.com/getkin/kin-openapi@v0.66.0/openapi3gen#example-package

**Comment by MarioCarrion** [comment]
Thanks @kishaningithub I'll take a look

**Comment by kishaningithub** [comment]
https://github.com/MarioCarrion/todo-api-microservice-example/issues/1#issuecomment-879696433

I hope this would also be addressed ☺️☺️

**Comment by MarioCarrion** [comment]
Yes, I'm still reading the new changes to see how the code can be updated to use that new package, I'm reopening this issue so I don't forget.

**Comment by kishaningithub** [comment]
Not stale

**Comment by kishaningithub** [comment]
Not stale
