### ISSUE TITLE
uuid-asap extension not necessary since Postgres 13

### ISSUE THREAD

**Issue by JanRuettinger** [MarioCarrion/todo-api-microservice-example#265]
In the [first migration file ](https://github.com/MarioCarrion/todo-api-microservice-example/blob/e9ea5758cc95fb9dfd6210aa56264dfbc215c657/db/migrations/20210218010009_create_tables.up.sql#L1) you load an extension called `uuid-ossp`.  Since Postgres 13 there is a function called `gen_random_uuid` which generates a uuid v4. Therefore, the extension `uuid-ossp` is not required anymore.

Here is link to the corresponding postgres [docs](https://www.postgresql.org/docs/current/functions-uuid.html).

Great work Mario!

**Comment by MarioCarrion** [comment]
Thanks for the suggestion @JanRuettinger. I added a new migration using this function instead.
